version: '3'
services:
  server:
    build:
      context: .
      args:
        - NODE_ENV=production
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
        - ACCOUNT_ID=${ACCOUNT_ID}
        - CLIENT_ID=${CLIENT_ID}
        - CLIENT_SECRET=${CLIENT_SECRET}
    env_file:
      - .env

    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    volumes:
      - type: bind
        source: ./.env
        target: ./build/.env
        read_only: true
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    restart: always
    volumes:
    - redis-data:/data
    expose:
    - ${REDIS_PORT}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
    
volumes:
  redis-data:

