version: '3.9'
services:
  server:
    build:
      context: .
      args:
        - NODE_ENV=production
        - NODE_PORT=${NODE_PORT}
        - REDIS_URL=${REDIS_URL}
        - REDIS_PORT=${REDIS_PORT}
        - ACCOUNT_ID=${ACCOUNT_ID}
        - CLIENT_ID=${CLIENT_ID}
        - CLIENT_SECRET=${CLIENT_SECRET}
    env_file:
      - .env
      - .env.prod
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  redis-data:

networks:
  default:
